### ISSUE TITLE
Agregar link a FB

### ISSUE THREAD

**Issue by afilgueira** [luchotc/sushiWeb#11]
Estoy pensando donde... se me ocurre que en el menu de arriba, podriamos dejar un espacio para poner un iconito blanco de FB que linkee a la pagina. Podemos probar cosas

**Comment by luchotc** [comment]
Lo agregué al menú arriba a la izquierda, mañana lo vemos bien.
Se podría poner el de whatsapp al costado que te scrollee abajo y te resalte el número del footer o algo así
