### ISSUE TITLE
Ultimos retoques

### ISSUE THREAD

**Issue by afilgueira** [luchotc/sushiWeb#12]
Buenas, dado que estan demasiado tranquilos, quisiera que liquidemos esto de nuestro lado y despues veremos si hace falta algun cambio
- Donde dice "Best sushi in town" poner "Sushi, platos orientales y catering"
- La frase que aparece abajo, y el boton de play/pausa, ocultarlos
- Agregar como primer horario "Martes a Viernes de 12:00hs a 15:00hs"
- El tag meta de "description" deberia decir tambien "Delivery de sushi, platos orientales y catering", para que cuando lo compartan en FB se vea bien.

Y una ultima cosa. Si no te jode, transferime el repo, asi lo pongo privado. No es nada del otro mundo, pero ya que github nos da repos infinitos privados, prefiero aprovecharlo.

Gracias!

**Comment by luchotc** [comment]
No me deja transferirlo por el fork que hiciste, avisame y te lo paso!

**Comment by afilgueira** [comment]
Oka, ahi borre el fork
